name: PR-Check

on:
  pull_request:

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set MAVEN_OPTS environment variable
        run: echo "MAVEN_OPTS=--add-opens jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-opens jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED" >> $GITHUB_ENV

#      - name: Install Maven
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y maven

      - name: Build with Maven
        run: mvn spotless:check checkstyle:check
#
#      - name: Run tests
#        run: mvn test
