name: Maven CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set MAVEN_OPTS
        run: echo "MAVEN_OPTS=--add-opens jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-opens jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED" >> $GITHUB_ENV

      - name: Set up Maven
        uses: actions/setup-maven@v2

      - name: Build with Maven
        run: mvn spotless:check checkstyle:check

      - name: Run tests
        run: mvn test
